### ISSUE TITLE
Crash on 1.12.2 due to Fire Arrows

### ISSUE THREAD

**Issue by Akitori** [Glitchfiend/Bullseye#16]
I was spamming fire arrows at a mountain when my server decided to drop dead. 

Forge 2509, minecraft 1.12.2, latest bullseye

crashlog here

[crash-2017-11-25_14.30.13-server.txt](https://github.com/Glitchfiend/Bullseye/files/1503336/crash-2017-11-25_14.30.13-server.txt)

**Comment by roxiecat** [comment]
I would like to add that I have also experienced crash issues when shooting arrows. I was firing fire arrows at Ents from Mo Creatures when my game suddenly crashed. Log:

```
Time: 4/6/19 1:03 AM
Description: Ticking entity
 
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockStateContainer{block=minecraft:tallgrass, properties=[type]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
    at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:288)
    at bullseye.entities.projectile.EntityBEArrow.func_184549_a(EntityBEArrow.java:491)
    at bullseye.entities.projectile.EntityBEArrow.func_70071_h_(EntityBEArrow.java:324)
    at net.minecraft.world.World.func_72866_a(World.java:1993)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1955)
    at net.minecraft.world.World.func_72939_s(World.java:1759)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
    at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:288)
    at bullseye.entities.projectile.EntityBEArrow.func_184549_a(EntityBEArrow.java:491)
    at bullseye.entities.projectile.EntityBEArrow.func_70071_h_(EntityBEArrow.java:324)
    at net.minecraft.world.World.func_72866_a(World.java:1993)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1955)
 
-- Entity being ticked --
Details:
    Entity Type: bullseye:arrow (bullseye.entities.projectile.EntityBEArrow)
    Entity ID: 3529
    Entity Name: Arrow
    Entity's Exact location: -66.33, 68.98, 172.98
    Entity's Block location: World: (-67,68,172), Chunk: (at 13,4,12 in -5,10; contains blocks -80,0,160 to -65,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: 0.01, -0.56, 0.25
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1759)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```
```
